name: Build
on:
  push:
    branches:
      - stable

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Use Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Build umd
      run: npm run build:umd
      
    - name: Deploy to npm
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        npm publish
      env:
        CI: true
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Build docs
      run: npm run build:docs

    - name: Deploy to gh-pages
      run: echo "TODO"